

-- Create database
USE PetCareX;
GO

/* =========================================================
   1) TABLES
   ========================================================= */

-- 1. CHINHANH
CREATE TABLE CHINHANH (
    MaCN VARCHAR(10) NOT NULL CONSTRAINT PK_CHINHANH PRIMARY KEY,
    TenCN NVARCHAR(100) NOT NULL,
    Diachi NVARCHAR(255) NULL,
    SDT VARCHAR(15) NULL,
    Giomocua TIME NULL,
    Giodongcua TIME NULL,
    CONSTRAINT CHK_CHINHANH_GioMoCua CHECK (Giomocua IS NULL OR Giodongcua IS NULL OR Giomocua <= Giodongcua)
);
GO

-- 2. KHACHHANG
CREATE TABLE KHACHHANG (
    MaKH VARCHAR(10) NOT NULL CONSTRAINT PK_KHACHHANG PRIMARY KEY,
    Hoten NVARCHAR(100) NOT NULL,
    CCCD VARCHAR(20) NULL,
    SDT VARCHAR(15) NULL,
    Email VARCHAR(100) NULL,
    Gioitinh NVARCHAR(10) NULL CONSTRAINT CHK_KHACHHANG_Gioitinh CHECK (Gioitinh IN (N'Nam', N'Nữ')),
    Ngaysinh DATE NULL,
    Bac NVARCHAR(20) NOT NULL CONSTRAINT DF_KHACHHANG_Bac DEFAULT N'Cơ bản'
        CONSTRAINT CHK_KHACHHANG_Bac CHECK (Bac IN (N'Cơ bản', N'Thân thiết', N'VIP')),
    Tichluy INT NOT NULL CONSTRAINT DF_KHACHHANG_Tichluy DEFAULT 0
        CONSTRAINT CHK_KHACHHANG_Tichluy CHECK (Tichluy >= 0),
    CONSTRAINT UQ_KHACHHANG_CCCD UNIQUE (CCCD)
);
GO

-- 3. TAIKHOAN_MATKHAU
CREATE TABLE TAIKHOAN_MATKHAU (
    MaKH VARCHAR(10) NOT NULL CONSTRAINT PK_TAIKHOAN_MATKHAU PRIMARY KEY,
    Tendangnhap VARCHAR(50) NOT NULL CONSTRAINT UQ_TAIKHOAN_Tendangnhap UNIQUE,
    Matkhau VARCHAR(255) NOT NULL,
    CONSTRAINT FK_TAIKHOAN_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
);
GO

-- 4. DICHVU
CREATE TABLE DICHVU (
    MaDV VARCHAR(10) NOT NULL CONSTRAINT PK_DICHVU PRIMARY KEY,
    TenDV NVARCHAR(100) NOT NULL
);
GO

-- 5. SANPHAM
CREATE TABLE SANPHAM (
    MaSP VARCHAR(10) NOT NULL CONSTRAINT PK_SANPHAM PRIMARY KEY,
    TenSP NVARCHAR(100) NOT NULL,
    LoaiSP NVARCHAR(50) NOT NULL, -- Thuốc, đồ ăn, đồ chơi...
    DonGia DECIMAL(18, 2) NOT NULL CONSTRAINT CHK_SANPHAM_DonGia CHECK (DonGia > 0)
);
GO

-- 6. VACCINE
CREATE TABLE VACCINE (
    MaVC VARCHAR(10) NOT NULL CONSTRAINT PK_VACCINE PRIMARY KEY,
    TenVC NVARCHAR(100) NOT NULL,
    NgaySanXuat DATE NULL,
    LieuLuong FLOAT NOT NULL CONSTRAINT CHK_VACCINE_LieuLuong CHECK (LieuLuong > 0),
    DonGia DECIMAL(18, 2) NOT NULL CONSTRAINT CHK_VACCINE_DonGia CHECK (DonGia > 0)
);
GO

-- 7. GOITIEMPHONG
CREATE TABLE GOITIEMPHONG (
    MaGoi VARCHAR(10) NOT NULL CONSTRAINT PK_GOITIEMPHONG PRIMARY KEY,
    TenGoi NVARCHAR(100) NOT NULL,
    ThoiGian INT NOT NULL CONSTRAINT CHK_GOI_ThoiGian CHECK (ThoiGian > 0), -- số tháng hiệu lực
    KhuyenMai FLOAT NOT NULL CONSTRAINT DF_GOI_KhuyenMai DEFAULT 0
        CONSTRAINT CHK_GOI_KhuyenMai CHECK (KhuyenMai BETWEEN 0 AND 100)
);
GO

-- 8. NHANVIEN
CREATE TABLE NHANVIEN (
    MaNV VARCHAR(10) NOT NULL CONSTRAINT PK_NHANVIEN PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE NULL,
    GioiTinh NVARCHAR(10) NULL CONSTRAINT CHK_NHANVIEN_GioiTinh CHECK (GioiTinh IN (N'Nam', N'Nữ')),
    ChucVu NVARCHAR(50) NOT NULL
        CONSTRAINT CHK_NHANVIEN_ChucVu CHECK (ChucVu IN (N'Bác sĩ thú y', N'Quản lí', N'Tiếp tân', N'Nhân viên bán hàng')),
    MaCN VARCHAR(10) NOT NULL,
    Luong DECIMAL(18, 2) NULL,
    Thuong DECIMAL(18, 2) NULL,
    CONSTRAINT FK_NHANVIEN_CN FOREIGN KEY (MaCN) REFERENCES CHINHANH(MaCN)
);
GO

-- 9. THUCUNG
CREATE TABLE THUCUNG (
    MaThuCung VARCHAR(10) NOT NULL CONSTRAINT PK_THUCUNG PRIMARY KEY,
    MaKH VARCHAR(10) NOT NULL,
    Ten NVARCHAR(50) NOT NULL,
    Loai NVARCHAR(50) NULL,
    Giong NVARCHAR(50) NULL,
    NgaySinh DATE NULL,
    GioiTinh NVARCHAR(10) NULL CONSTRAINT CHK_THUCUNG_GioiTinh CHECK (GioiTinh IN (N'Đực', N'Cái')),
    TinhTrangSK NVARCHAR(MAX) NULL,
    CONSTRAINT FK_THUCUNG_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
);
GO

-- 10. CHINHANH_SANPHAM (kho)
CREATE TABLE CHINHANH_SANPHAM (
    MaCN VARCHAR(10) NOT NULL,
    MaSP VARCHAR(10) NOT NULL,
    SoLuongTonKho INT NOT NULL CONSTRAINT DF_CNSP_Ton DEFAULT 0
        CONSTRAINT CHK_CNSP_Ton CHECK (SoLuongTonKho >= 0),
    CONSTRAINT PK_CHINHANH_SANPHAM PRIMARY KEY (MaCN, MaSP),
    CONSTRAINT FK_CNSP_CN FOREIGN KEY (MaCN) REFERENCES CHINHANH(MaCN),
    CONSTRAINT FK_CNSP_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);
GO

-- 10b. CHINHANH_VACCINE (kho)
CREATE TABLE CHINHANH_VACCINE (
    MaCN VARCHAR(10) NOT NULL,
    MaVC VARCHAR(10) NOT NULL,
    SoLuongTonKho INT NOT NULL CONSTRAINT DF_CNV_Ton DEFAULT 0
        CONSTRAINT CHK_CNV_Ton CHECK (SoLuongTonKho >= 0),
    CONSTRAINT PK_CHINHANH_VACCINE PRIMARY KEY (MaCN, MaVC),
    CONSTRAINT FK_CNV_CN FOREIGN KEY (MaCN) REFERENCES CHINHANH(MaCN),
    CONSTRAINT FK_CNV_VC FOREIGN KEY (MaVC) REFERENCES VACCINE(MaVC)
);
GO

-- 11. HOADON
CREATE TABLE HOADON (
    MaHoaDon VARCHAR(10) NOT NULL CONSTRAINT PK_HOADON PRIMARY KEY,
    NgayLap DATETIME NOT NULL CONSTRAINT DF_HOADON_NgayLap DEFAULT GETDATE(),
    NhanVienLap VARCHAR(10) NOT NULL,
    MaKH VARCHAR(10) NOT NULL,
    TongTien DECIMAL(18, 2) NOT NULL CONSTRAINT DF_HOADON_TongTien DEFAULT 0,
    KhuyenMai FLOAT NOT NULL CONSTRAINT DF_HOADON_KhuyenMai DEFAULT 0
        CONSTRAINT CHK_HOADON_KhuyenMai CHECK (KhuyenMai BETWEEN 0 AND 100),
    HinhThucThanhToan NVARCHAR(50) NOT NULL
        CONSTRAINT CHK_HOADON_HTTT CHECK (HinhThucThanhToan IN (N'Chuyển khoản', N'Tiền mặt')),
    CONSTRAINT FK_HOADON_NV FOREIGN KEY (NhanVienLap) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_HOADON_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
);
GO

-- 12. PHIENDICHVU
CREATE TABLE PHIENDICHVU (
    MaPhien VARCHAR(10) NOT NULL CONSTRAINT PK_PHIENDICHVU PRIMARY KEY,
    MaHoaDon VARCHAR(10) NOT NULL,
    MaThuCung VARCHAR(10) NOT NULL,
    MaDV VARCHAR(10) NOT NULL,
    GiaTien DECIMAL(18, 2) NOT NULL CONSTRAINT CHK_PDV_GiaTien CHECK (GiaTien >= 0),
    CONSTRAINT FK_PDV_HD FOREIGN KEY (MaHoaDon) REFERENCES HOADON(MaHoaDon),
    CONSTRAINT FK_PDV_TC FOREIGN KEY (MaThuCung) REFERENCES THUCUNG(MaThuCung),
    CONSTRAINT FK_PDV_DV FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV)
);
GO

-- 13. KHAMBENH
CREATE TABLE KHAMBENH (
    MaPhien VARCHAR(10) NOT NULL CONSTRAINT PK_KHAMBENH PRIMARY KEY,
    BacSiPhuTrach VARCHAR(10) NOT NULL,
    CacTrieuChung NVARCHAR(MAX) NULL,
    ChanDoan NVARCHAR(MAX) NULL,
    NgayTaiKham DATE NULL,
    CONSTRAINT FK_KB_PDV FOREIGN KEY (MaPhien) REFERENCES PHIENDICHVU(MaPhien),
    CONSTRAINT FK_KB_BS FOREIGN KEY (BacSiPhuTrach) REFERENCES NHANVIEN(MaNV)
);
GO

-- 14. TOATHUOC
CREATE TABLE TOATHUOC (
    MaPhien VARCHAR(10) NOT NULL,
    MaThuoc VARCHAR(10) NOT NULL,
    Soluong INT NOT NULL CONSTRAINT CHK_TOATHUOC_Soluong CHECK (Soluong > 0),
    CONSTRAINT PK_TOATHUOC PRIMARY KEY (MaPhien, MaThuoc),
    CONSTRAINT FK_TOATHUOC_PDV FOREIGN KEY (MaPhien) REFERENCES PHIENDICHVU(MaPhien),
    CONSTRAINT FK_TOATHUOC_SP FOREIGN KEY (MaThuoc) REFERENCES SANPHAM(MaSP)
);
GO

-- 15. TIEMPHONG
CREATE TABLE TIEMPHONG (
    MaPhien VARCHAR(10) NOT NULL CONSTRAINT PK_TIEMPHONG PRIMARY KEY,
    MaVC VARCHAR(10) NOT NULL,
    MaGoi VARCHAR(10) NULL,
    BacSiPhuTrach VARCHAR(10) NOT NULL,
    NgayTiem DATE NOT NULL,
    SoLieu FLOAT NOT NULL CONSTRAINT CHK_TIEMPHONG_SoLieu CHECK (SoLieu > 0),
    CONSTRAINT FK_TP_PDV FOREIGN KEY (MaPhien) REFERENCES PHIENDICHVU(MaPhien),
    CONSTRAINT FK_TP_VC FOREIGN KEY (MaVC) REFERENCES VACCINE(MaVC),
    CONSTRAINT FK_TP_GOI FOREIGN KEY (MaGoi) REFERENCES GOITIEMPHONG(MaGoi),
    CONSTRAINT FK_TP_BS FOREIGN KEY (BacSiPhuTrach) REFERENCES NHANVIEN(MaNV)
);
GO

-- 16. NHANXET
CREATE TABLE NHANXET (
    MaKH VARCHAR(10) NOT NULL,
    MaHoaDon VARCHAR(10) NOT NULL,
    DiemDV INT NULL CONSTRAINT CHK_NX_DiemDV CHECK (DiemDV BETWEEN 1 AND 10),
    Mucdohailong INT NULL CONSTRAINT CHK_NX_Hailong CHECK (Mucdohailong BETWEEN 1 AND 5),
    Thaidonhanvien NVARCHAR(MAX) NULL,
    Binhluan NVARCHAR(MAX) NULL,
    CONSTRAINT PK_NHANXET PRIMARY KEY (MaKH, MaHoaDon),
    CONSTRAINT FK_NX_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    CONSTRAINT FK_NX_HD FOREIGN KEY (MaHoaDon) REFERENCES HOADON(MaHoaDon)
);
GO

/* ====== 6 bảng bổ sung theo báo cáo ====== */

-- CUNGCAPDICHVU(MaCN, MaDV)
CREATE TABLE CUNGCAPDICHVU (
    MaCN VARCHAR(10) NOT NULL,
    MaDV VARCHAR(10) NOT NULL,
    CONSTRAINT PK_CUNGCAPDICHVU PRIMARY KEY (MaCN, MaDV),
    CONSTRAINT FK_CCDV_CN FOREIGN KEY (MaCN) REFERENCES CHINHANH(MaCN),
    CONSTRAINT FK_CCDV_DV FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV)
);
GO

-- MUAHANG(MaPhien, MaSP, SoLuong)
CREATE TABLE MUAHANG (
    MaPhien VARCHAR(10) NOT NULL,
    MaSP VARCHAR(10) NOT NULL,
    SoLuong INT NOT NULL CONSTRAINT CHK_MUAHANG_SoLuong CHECK (SoLuong > 0),
    CONSTRAINT PK_MUAHANG PRIMARY KEY (MaPhien, MaSP),
    CONSTRAINT FK_MH_PDV FOREIGN KEY (MaPhien) REFERENCES PHIENDICHVU(MaPhien),
    CONSTRAINT FK_MH_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);
GO

-- GOITIEMPHONG_VACCINE(MaGoi, MaVC, SoLieu)
CREATE TABLE GOITIEMPHONG_VACCINE (
    MaGoi VARCHAR(10) NOT NULL,
    MaVC VARCHAR(10) NOT NULL,
    SoLieu FLOAT NOT NULL CONSTRAINT CHK_GTPVC_SoLieu CHECK (SoLieu > 0),
    CONSTRAINT PK_GTPVC PRIMARY KEY (MaGoi, MaVC),
    CONSTRAINT FK_GTPVC_GOI FOREIGN KEY (MaGoi) REFERENCES GOITIEMPHONG(MaGoi),
    CONSTRAINT FK_GTPVC_VC FOREIGN KEY (MaVC) REFERENCES VACCINE(MaVC)
);
GO

-- MUA_GOI(MaKH, MaGoi, MaHoaDon)
CREATE TABLE MUA_GOI (
    MaKH VARCHAR(10) NOT NULL,
    MaGoi VARCHAR(10) NOT NULL,
    MaHoaDon VARCHAR(10) NOT NULL,
    CONSTRAINT PK_MUA_GOI PRIMARY KEY (MaKH, MaGoi, MaHoaDon),
    CONSTRAINT FK_MUAGOI_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    CONSTRAINT FK_MUAGOI_GOI FOREIGN KEY (MaGoi) REFERENCES GOITIEMPHONG(MaGoi),
    CONSTRAINT FK_MUAGOI_HD FOREIGN KEY (MaHoaDon) REFERENCES HOADON(MaHoaDon)
);
GO

-- GOI_KHACHHANG_VACCINE(MaKH, MaGoi, MaVC, Solieuconlai)
CREATE TABLE GOI_KHACHHANG_VACCINE (
    MaKH VARCHAR(10) NOT NULL,
    MaGoi VARCHAR(10) NOT NULL,
    MaVC VARCHAR(10) NOT NULL,
    Solieuconlai FLOAT NOT NULL CONSTRAINT CHK_GKHV_SoLieu CHECK (Solieuconlai >= 0),
    CONSTRAINT PK_GKHV PRIMARY KEY (MaKH, MaGoi, MaVC),
    CONSTRAINT FK_GKHV_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    CONSTRAINT FK_GKHV_GOI FOREIGN KEY (MaGoi) REFERENCES GOITIEMPHONG(MaGoi),
    CONSTRAINT FK_GKHV_VC FOREIGN KEY (MaVC) REFERENCES VACCINE(MaVC)
);
GO

-- LICHSUDIEUDONG(MaNV, MaCN, NgayBD, NgayKT, ChucVu)
CREATE TABLE LICHSUDIEUDONG (
    MaNV VARCHAR(10) NOT NULL,
    MaCN VARCHAR(10) NOT NULL,
    NgayBD DATE NOT NULL,
    NgayKT DATE NOT NULL,
    ChucVu NVARCHAR(50) NOT NULL
        CONSTRAINT CHK_LSDD_ChucVu CHECK (ChucVu IN (N'Bác sĩ thú y', N'Quản lí', N'Tiếp tân', N'Nhân viên bán hàng')),
    CONSTRAINT PK_LICHSUDIEUDONG PRIMARY KEY (MaNV, MaCN, NgayBD),
    CONSTRAINT FK_LSDD_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_LSDD_CN FOREIGN KEY (MaCN) REFERENCES CHINHANH(MaCN),
    CONSTRAINT CHK_LSDD_Ngay CHECK (NgayBD < NgayKT)
);
GO

CREATE SEQUENCE dbo.SEQ_KHACHHANG
    AS INT
    START WITH 1
    INCREMENT BY 1;
GO